### ISSUE TITLE
3d printing

### ISSUE THREAD

**Issue by trose-neuro** [jinook0707/openfeeder#1]
Dear all,

this looks really nice! Thanks a lot for sharing!

Did you, by any chance, also design a 3d printable version? This would be very helpful for us...

Best wishes,
Tobias

**Comment by jinook0707** [comment]
Hi Tobias,

Thanks for your message.
Unfortunately, I didn't make a 3D printable version for this project.

Best regards,
Jinook

**Comment by trose-neuro** [comment]
Thanks!
